version: '3'
services: 
  #first container is responsible for deployment
  web: 
    build:
    # you need to define the name of Dockerfile.dev under the context
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      #. current folder outside the container 
      #:/app the app folder inside the container
      - .:/app 
  #second container is responsible for testing
  tests:
    build: 
      context: . 
      dockerfile: Dockerfile.dev 
    volumes: 
      - /app/node_modules
      - .:/app 
    command: ["npm", "run", "test"]